pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - npm ci --prefix ./expresence
    - npm run build --prefix ./expresence
    - mv ./expresence/public ./expresence/public-vue # GitLab Pages hooks on the public folder
    - ls ./expresence/
    - mv ./expresence/dist ./expresence/public # rename the dist folder (result of npm run build)
    - ls ./expresence/public
    
  artifacts:
    paths:
      - public/ # artifact path must be /public for GitLab Pages to pick it up
  only:
    - main