variables:
   CLIENT_ID: $CLIENT_ID
   AUTHORITY: $AUTHORITY
   REDIRECT_URI: $REDIRECT_URI
   POST_LOGOUT_REDIRECT_URI: $POST_LOGOUT_REDIRECT_URI
   
pages: # the job must be named pages
  image: node:latest
  stage: deploy
  script:
    - npm ci --prefix ./expresence
    - npm run build --prefix ./expresence
    - mv ./expresence/public ./expresence/public-vue # GitLab Pages hooks on the public folder
    - mkdir public
    - mv ./expresence/dist/* public # rename the dist folder (result of npm run build)
    - ls public
    
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - main