# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
stages:
  - build
#  - test
#  - deploy

workflow:
  name: "Pipeline for branch: $CI_COMMIT_BRANCH"
  
build-job:
  stage: build
  image: node
  script:
    - echo "Running 'npm install' command..."
    - npm  install --prefix ./expresence
    - echo "Running 'npm run build' command..."
    - npm run build --prefix ./expresence
  artifacts:
    paths:
      - "/build"