variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: $CI_PROJECT_DIR/expresence
  OUTPUT_PATH: $CI_PROJECT_DIR/expresence/dist

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
    - echo $APP_PATH
    - echo $OUTPUT_PATH
  only:
    - main