name: Deploy to Github Page
on:
  push:
    branches: [ "main" ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2

    - name: Build and deploy app to gh-pages
      run: |
        npm ci
        npm run build
      working-directory: ./expresence
    - name: deploy to gh-pages
      run: |
        echo "Current folder path: $PWD"
        ls
        git config user.email "amin.yassin@live.com"
        git config user.name "aminsys"
        git init
        git add -A
        git commit -m 'Deploy to Github Pages - run number: $GITHUB_RUN_NUMBER'
        git push -f https://aminsys:${{ secrets.GITHUB_TOKEN }}@github.com/aminsys/Expresence.git master:gh-pages
      shell: bash
        
