name: Deploy to Github Page
on:
  push:
    branches: [ "main" ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Navigate to expresence folder
      run: cd ./expresence
    - name: Install dependencies
      run: npm install
    - name: Build project Expresence
      run: npm run build --prefix ./expresence

    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'aminsys'
        reponame: 'Expresence'
        token: ${{ secrets.GITHUB_TOKEN }}
